provider:
  name: faas
  gateway: http://localhost:8080

functions:
  rls:
    lang: python
    handler: ./rls
    image: ems5311/rls:latest

  nameispresent:
    lang: node
    handler: ./nameispresent
    image: ems5311/nameispresent:latest

  gif-maker:
    lang: Dockerfile
    handler: ./gif-maker
    image: ems5311/gif-maker:0.1

  youtube-dl:
    lang: Dockerfile
    handler: ./youtube-dl
    image: ems5311/youtube-dl:0.1

# Event a comment will re-publish the functions.
# cool!
# hello
