provider:
  name: faas
  gateway: http://localhost:8080

functions:
  rls:
    lang: python
    handler: ./rls
    image: ems5311/rls:latest

  nameispresent:
    lang: node
    handler: ./nameispresent
    image: ems5311/nameispresent:latest

  gif-maker:
    image: ems5311/gif-maker:latest
    fprocess: ./entry.sh

  youtube-dl:
    image: ems5311/youtube-dl:latest
    fprocess: ./entry.sh

# Event a comment will re-publish the functions.
# cool!
# hello
